spring:
  data:
    redis:
      host: 192.168.191.136
      port: 6379
      database: 0
      password: password
      timeout: 1800000 #連接超時時間(ms)
      lettuce:
        pool:
          max-active: 20 #最大連接數
          max-wait: -1 #最大阻塞等待時間(ms，負數為沒有限制)
          max-idle: 5 #最大空閒連接
          min-idle: 0 #最小空閒連接